### ISSUE TITLE
Issue - creating Fibonacci series in Python

### ISSUE THREAD

**Issue by satishjasthi** [hacktoberfest17/programming#104]

**Comment by lakshayg** [comment]
Can I take this up?

**Comment by t2013anurag** [comment]
@satishjasthi is picking it up, i guess. Meanwhile you can create your own issue and submit a pr.

**Comment by satishjasthi** [comment]
I'm working on this

**Comment by DamiyanVC** [comment]
i would like to submit a pr in it

**Comment by t2013anurag** [comment]
@DamiyanVC - you can create another issue and submit a pr for it.

**Comment by DamiyanVC** [comment]
ok

**Comment by satishjasthi** [comment]
@t2013anurag - I'm unable to push my change 
>>> git push origin satishjasthi_fibonacci_in_python 
remote: Permission to hacktoberfest17/programming.git denied to satishjasthi.
fatal: unable to access 'https://github.com/hacktoberfest17/programming.git/': The requested URL returned error: 403

**Comment by satishjasthi** [comment]
t2013anurag - I have requested a pull request can you please verify and merge it to master
Thank you
