### ISSUE TITLE
Factorial in Python

### ISSUE THREAD

**Issue by tanmaydatta** [hacktoberfest17/programming#115]
Code will give runtime error in case of `factorial(0)`
https://ideone.com/3MZzi7
@PiyushPawar17

**Comment by t2013anurag** [comment]
@tanmaydatta @PiyushPawar17  can anyone of you fix it?

**Comment by tanmaydatta** [comment]
https://github.com/hacktoberfest17/programming/pull/116

**Comment by t2013anurag** [comment]
Fixed with #116
