### ISSUE TITLE
Binary Search in Java

### ISSUE THREAD

**Issue by KaveeshBaddage** [hacktoberfest17/programming#161]
I would like to add a code about binary search in Java.

**Comment by chawki27000** [comment]
I take this one

**Comment by KaveeshBaddage** [comment]
I have already started.. @chawki27000

**Comment by chawki27000** [comment]
@KaveeshBaddage thank you to prevent me, i will find others contribution.

**Comment by KaveeshBaddage** [comment]
I added pull request on Binary Search in Java . 
https://github.com/hacktoberfest17/programming/pull/173
