### ISSUE TITLE
Factorial Python

### ISSUE THREAD

**Issue by starsunny** [hacktoberfest17/programming#240]
#!/bin/env python
# change the value for a different result
num = 7

# uncomment to take input from the user
#num = int(input("Enter a number: "))

factorial = 1

# check if the number is negative, positive or zero
if num < 0:
   print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
   print("The factorial of 0 is 1")
else:
   for i in range(1,num + 1):
       factorial = factorial*i
   print("The factorial of",num,"is",factorial)

**Comment by szepnapot** [comment]
I'll do it.
