### ISSUE TITLE
Program to find reverse of a number

### ISSUE THREAD

**Issue by suhitmajumdar** [hacktoberfest17/programming#33]
The given issue contains a program in c++ to find the reverse of any number.
#include <iostream>
using namespace std;

int main()
{
    int n, reversedNumber = 0, remainder;

    cout << "Enter an integer: ";
    cin >> n;

    while(n != 0)
    {
        remainder = n%10;
        reversedNumber = reversedNumber*10 + remainder;
        n /= 10;
    }

    cout << "Reversed Number = " << reversedNumber;

    return 0;
}

**Comment by Jish80** [comment]
Can I do one in python3?

**Comment by t2013anurag** [comment]
@Jish80 - yeah sure, create a separate issue for that.
