### ISSUE TITLE
write an encryption algorithm which uses a user defined salt and a pre-defined encryption method.

### ISSUE THREAD

**Issue by t2013anurag** [hacktoberfest17/programming#464]

**Comment by SourceNode** [comment]
I'm interested in this issue. Would I be able to use an existing open source encryption engine (like BouncyCastle) internally, or are you expecting the algorithm to be written from scratch? I would use Java as my programming language of choice.

**Comment by t2013anurag** [comment]
@SourceNode - it's your choice, you can use a library as well. The only condition is that you need to write a wrapper around the salt method, i.e. user's can choose their own salt value.

Also make sure you write a proper README.md for the directory.
