### ISSUE TITLE
write a script to fetch contributors from github api and fill the required details in the Contributors.md file.

### ISSUE THREAD

**Issue by t2013anurag** [hacktoberfest17/programming#467]

**Comment by vkdrn** [comment]
@t2013anurag Hi. What programming language should it be written?

**Comment by MadKat13** [comment]
I can take this.
@t2013anurag do you have any preferences about a language? Else I would code it in Python

**Comment by t2013anurag** [comment]
@MadKat13 no such preferences.

**Comment by t2013anurag** [comment]
I need a script so that I can run it as a cron job and update it every 3 hours or so.

**Comment by MadKat13** [comment]
Ok yeah I will work on it

**Comment by MadKat13** [comment]
@t2013anurag
Where do you want the script to be? So that I can take the relative path to the contributors.md

**Comment by t2013anurag** [comment]
@MadKat13 - keep it in the parent directory.
