### ISSUE TITLE
Add the following items in the Readme and contributing files

### ISSUE THREAD

**Issue by t2013anurag** [hacktoberfest17/programming#49]
-  The issue should be labelled Hacktoberfest.
-  Milestone should be added.
-  Self assigned after creating.

**Comment by t2013anurag** [comment]
See the example of what I have done.

**Comment by vkdrn** [comment]
@t2013anurag I'll take this one

**Comment by t2013anurag** [comment]
Closing since, first-time contributors can't self assign the issues and add labels.
