### ISSUE TITLE
improve the ui of the gh-pages.

### ISSUE THREAD

**Issue by t2013anurag** [hacktoberfest17/programming#706]
https://hacktoberfest17.github.io/programming/ - is the current ui. The index.html file resides inside the gh-pages branch.

**Comment by eric-horvat** [comment]
Keen to give this one a go

**Comment by t2013anurag** [comment]
@eric-horvat - sure.

**Comment by eric-horvat** [comment]
Do you have any requirements for the updated UI? For instance, that it still uses materialize?

**Comment by t2013anurag** [comment]
@eric-horvat no such requirements, you can use what ever libraries you want.

**Comment by bhansa** [comment]
@t2013anurag you just need to update the index.html file in `gh-pages` from `master` as it is already there.

**Comment by codlocker** [comment]
@t2013anurag I have added a few design changes which was hindering the view of Username. You can go through my PR!
