### ISSUE TITLE
Addition of 2 numbers in C++

### ISSUE THREAD

**Issue by ShreyasheeS** [hacktoberfest17/programming#755]
Write a program in C++ to add 2 numbers. 
P.S. : This issue has been raised solely for the purpose of Hacktoberfest.

**Comment by PiyushPawar17** [comment]
@t2013anurag - This is program is too basic, isn't it?

**Comment by ShreyasheeS** [comment]
@PiyushPawar17 I can make another issue with a better program. However, I wanted to know if its possible that a user creates their own issue and solves it on their own?

**Comment by ShreyasheeS** [comment]
@PiyushPawar17 Hacktoberfest asks us to solve issues with Hacktoberfest label on them. I can't find beginner issues with the same label.

**Comment by PiyushPawar17** [comment]
@ShreyasheeS - Yes, they can. I'm doing the same.

**Comment by PiyushPawar17** [comment]
@ShreyasheeS - The labels will be added by admin. Just create an issue and send PR.

**Comment by ShreyasheeS** [comment]
@PiyushPawar17 In which directory must I add my new file(s)?

**Comment by PiyushPawar17** [comment]
@ShreyasheeS - If the program you want to add don't have the corresponding directory, create one and add your program in it. Else add it in the existing directory.
