### ISSUE TITLE
Implement SinglyLinkedList in java

### ISSUE THREAD

**Issue by vaibhav6451956** [hacktoberfest17/programming#872]
fixes #868

**Comment by vaibhav6451956** [comment]
@knightcube  Cannot add/edit the label for this PR to be reflected in my stats. Please help.

**Comment by knightcube** [comment]
yes dear everyone faces this problem as a newbie . You wont be able to edit the label as you are a contributor. The label is added/edited by a collaborator. If he gives you the rights you can also do that. 
I had the same question so i "googled" it and this is what came up and it will answer ur question as well- https://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner
I dont know why but it was not written in the official github docs. Anyway i guess i solved your issue. :)

**Comment by vaibhav6451956** [comment]
@knightcube  Thanks mate for the detailed answer..it was quite helpful! 👍
