### ISSUE TITLE
Creating Factorial program in Python

### ISSUE THREAD

**Issue by PiyushPawar17** [hacktoberfest17/programming#90]

**Comment by Latterization** [comment]
Can I start on this?

**Comment by PiyushPawar17** [comment]
It's already merged

**Comment by t2013anurag** [comment]
@PiyushPawar17  - close issues when your PR get's merged.

Better practice is to reference the issue while creating the commit. The commit name can contain #91 fixes or something.

**Comment by PiyushPawar17** [comment]
OK 👍
