### ISSUE TITLE
Add Binary Search in python3

### ISSUE THREAD

**Issue by KaveeshBaddage** [hacktoberfest17/programming#92]

**Comment by KaveeshBaddage** [comment]
I would like to add a commit about this issue.

**Comment by t2013anurag** [comment]
@KaveeshBaddage - sure, go ahead.

**Comment by Latterization** [comment]
Can I start on this?

**Comment by KaveeshBaddage** [comment]
I already started

**Comment by KaveeshBaddage** [comment]
I created a pull request.  @t2013anurag . 
https://github.com/hacktoberfest17/programming/pull/95

**Comment by Latterization** [comment]
Good luck!

**Comment by KaveeshBaddage** [comment]
@Latterization  Thank You..

**Comment by t2013anurag** [comment]
@Latterization - You can add any other program, create your own issue and submit a pr.

**Comment by KaveeshBaddage** [comment]
Pull request is accepted.
