### ISSUE TITLE
Add Javascript/React version of Tic-Tac-Toe

### ISSUE THREAD

**Issue by robertspurlin** [hacktoberfest17/programming#991]
fixes #997

**Comment by bhansa** [comment]
I have added a javascript app implementation here #976  see the last commit. Sorry, I forgot to put it in a  different branch.

**Comment by t2013anurag** [comment]
@bhansa - https://github.com/hacktoberfest17/programming/tree/master/games_dev/TicTacToe

The similar code exists here, make sure you have a different implementation and push the code in a separate PR and in a separate branch.

**Comment by t2013anurag** [comment]
Remove the commits from that branch.
